### ISSUE TITLE
Crashed

### ISSUE THREAD

**Issue by yourrree** [Guichaguri/TickrateChanger#14]
Hi! So I use tickrate changer in 1.12.2 forge (It works) but when i log into a single player world my game crashes any resolution to this?

**Comment by EFWGithubMC** [comment]
I have a similar issue, just like yours, but my game crashes when I log off the world. 
The crash report says this:
**Description: Exception ticking world
java.lang.IllegalStateException: TickNextTick list out of synch
    at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:691)
    at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:223)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)**
Does yours crash report look like this as well?
